### ISSUE TITLE
Download command doesn't work

### ISSUE THREAD

**Issue by guitsaru** [polm/unidic-py#1]
When I run the commands from the Readme:
```bash
pip install unidic
python -m unidic download
```
I get the following output:
```
✘ You imported unidic, but dictionary data is not installed. Run this
command to install the latest UniDic:     python -m unidic download
```

**Comment by polm** [comment]
Well that's embarrassing, there were a couple of reasons that was broken. I think they should be fixed now. Can you try `pip install unidic==1.0.1rc1`?

**Comment by guitsaru** [comment]
Yep, it works now. Thanks!

**Comment by polm** [comment]
Great, thanks for confirming! 

v1.0.1 has been released so this should be fully resolved now.
