### ISSUE TITLE
spoken or written?

### ISSUE THREAD

**Issue by garfieldnate** [polm/unidic-py#11]
The readme does not state whether this uses the spoken or written Japanese variant of Unidic, but it would be ideal to be able to choose which one is downloaded.

**Comment by polm** [comment]
This is UniDic for Contemporary Written Japanese, I have added a note to the README. 

I have never needed the one for spoken Japanese, and I think I've had a request for it maybe once before this, so I'm not inclined to package it. But if someone else wants to I'd be happy to link to it from the README, for example.

**Comment by garfieldnate** [comment]
I sort of assumed that it would be the much better choice for most internet or popular media (tweets, blogs, manga, movie subtitles, etc.). My issue is that I can't find any quick way to test it out, and I haven't seen any demos or anything, so I don't actually know if I'm missing out on improved accuracy in my domain.

If my project budget allows, I'll try to open a new branch that uses the spoken Unidic and then do some comparisons. After that, I'd be happy to send a PR, or else just leave the branch up publicly.

**Comment by polm** [comment]
That makes sense. If you just want to test spoken UniDic you don't need to package it like I have CWJ UniDic here - you can just download it, unzip it, and specify the path directly using MeCab (`-d dicdir`).

**Comment by garfieldnate** [comment]
Took me down a rabbit hole a bit, but I've found that for colloquial expressions the older Unidic versions seem to give slightly better segmentations than the newest ones. So I'll just use your unidic-lite package for now.

**Comment by polm** [comment]
OK, got it. 

Since there is nothing for me to do here I'm going to close this, but if anyone packages other UniDics feel free to let me know.
