### ISSUE TITLE
is it possible to retrieve the common kana representation?

### ISSUE THREAD

**Issue by garfieldnate** [polm/unidic-py#12]
The documentation of this package says:
>kana: 読みがな, this is the typical representation of a word in kana, unlike pron. 講師 is こうし.

However, my observation is that the `kana` field always contains katakana. For example, if you go to the streamlit demo app and type in `もうバレタぞ、講師の名前`, you get this:

![image](https://user-images.githubusercontent.com/778453/203033513-8efe27c3-0747-43fe-a15b-e06c1b9131ad.png)

The same issue exists with unidic-lite. The documentation appears wrong, but the bigger problem for me is that I really want the correct kana representations. Is it possible to retrieve these any other way?

**Comment by garfieldnate** [comment]
Locating the relevant lines in the Unidic source, I don't see the correct hiragana spelling anywhere:

　　　　講師,1143,2885,2294,名詞,普通名詞,一般,*,*,*,コウシ,講師,講師,コーシ,講師,コーシ,漢,*,*,*,*,*,*,体,コウシ,コウシ,コウシ,コウシ,1,C1,*,3318609594163712,12073
　　　　講師,1143,2885,6616,名詞,普通名詞,一般,*,*,*,コウシ,講師,講師,コージ,講師,コージ,漢,*,*,*,*,*,*,体,コウジ,コウジ,コウジ,コウジ,1,C1,*,3318618184098304,12073

I think perhaps what is meant by "typical representation" refers to using the 長音符 vs. a kana letter for writing (noted already in the doc for the `pron` field). So the pronunciation is コーシ while the kana spelling is コウシ. While this might be useful info, it doesn't tell us whether a word is typically spelled with hiragana or katakana (plant and animal names, foreign names, etc.). Surface forms can vary, and the lemma form will be a kanji representation if one exists. So it seems like using only Unidic it's not possible to fully specify the typical kana representation of a word. I think all that can be done here is to update the documentation:

>kana: 読みがな, this is the typical kana spelling of a word, in katakana. 講師 is コウシ. Note that it is not possible to determine whether a word is typically spelled in hiragana or katakana.

**Comment by polm** [comment]
> I think perhaps what is meant by "typical representation" refers to using the 長音符 vs. a kana letter for writing (noted already in the doc for the pron field). So the pronunciation is コーシ while the kana spelling is コウシ. While this might be useful info, it doesn't tell us whether a word is typically spelled with hiragana or katakana (plant and animal names, foreign names, etc.). 

Your understanding is correct. Information about the typical way a word is written is not available in UniDic, though the lemma is vaguely similar, and you can use `goshu` to find if the word is 外来語 or whatever.

I will update the docs to be clear about this.

**Comment by polm** [comment]
Updated the docs, so I'll close this.
